const questions = [
  {
    id: 1,
    question: "¿Cuál es la capital de Francia?",
    options: ["Ankara", "Londres", "París", "Varsovia"],
    correctIndex: 2,
  },
  {
    id: 2,
    question: "¿Cuál es la capital de Italia?",
    options: ["Helsinki", "Bratislava", "Antananarivo", "Roma"],
    correctIndex: 3,
  },
  {
    id: 3,
    question: "¿Cuál es la capital de Alemania?",
    options: ["Oslo", "Londres", "Berlín", "Dublín"],
    correctIndex: 2,
  },
  {
    id: 4,
    question: "¿Cuál es la capital de Portugal?",
    options: ["Tallin", "Hanói", "Lisboa", "Katmandú"],
    correctIndex: 2,
  },
  {
    id: 5,
    question: "¿Cuál es la capital de Reino Unido?",
    options: ["Londres", "París", "El Cairo", "Singapur"],
    correctIndex: 0,
  },
  {
    id: 6,
    question: "¿Cuál es la capital de Irlanda?",
    options: ["El Cairo", "Dublín", "Zagreb", "Maputo"],
    correctIndex: 1,
  },
  {
    id: 7,
    question: "¿Cuál es la capital de Bélgica?",
    options: ["Bruselas", "Copenhague", "Oslo", "Ciudad de Panamá"],
    correctIndex: 0,
  },
  {
    id: 8,
    question: "¿Cuál es la capital de Países Bajos?",
    options: ["Malé", "Asunción", "Dublín", "Ámsterdam"],
    correctIndex: 3,
  },
  {
    id: 9,
    question: "¿Cuál es la capital de Suiza?",
    options: ["Bangkok", "Berna", "Amán", "Nairobi"],
    correctIndex: 1,
  },
  {
    id: 10,
    question: "¿Cuál es la capital de Austria?",
    options: ["Berna", "Viena", "Dublín", "Ulán Bator"],
    correctIndex: 1,
  },
  {
    id: 11,
    question: "¿Cuál es la capital de Grecia?",
    options: ["Atenas", "Ciudad de Panamá", "La Valeta", "Copenhague"],
    correctIndex: 0,
  },
  {
    id: 12,
    question: "¿Cuál es la capital de Suecia?",
    options: ["Estocolmo", "Ciudad de Guatemala", "San José", "Belgrado"],
    correctIndex: 0,
  },
  {
    id: 13,
    question: "¿Cuál es la capital de Noruega?",
    options: ["Taskent", "Teherán", "Bakú", "Oslo"],
    correctIndex: 3,
  },
  {
    id: 14,
    question: "¿Cuál es la capital de Dinamarca?",
    options: ["Copenhague", "Malé", "Tirana", "Islamabad"],
    correctIndex: 0,
  },
  {
    id: 15,
    question: "¿Cuál es la capital de Finlandia?",
    options: ["Helsinki", "Astaná", "Ankara", "Túnez"],
    correctIndex: 0,
  },
  {
    id: 16,
    question: "¿Cuál es la capital de Polonia?",
    options: ["La Valeta", "Ámsterdam", "Lusaka", "Varsovia"],
    correctIndex: 3,
  },
  {
    id: 17,
    question: "¿Cuál es la capital de Hungría?",
    options: ["Vilna", "Túnez", "Budapest", "Berna"],
    correctIndex: 2,
  },
  {
    id: 18,
    question: "¿Cuál es la capital de República Checa?",
    options: ["Teherán", "Praga", "Asunción", "Santo Domingo"],
    correctIndex: 1,
  },
  {
    id: 19,
    question: "¿Cuál es la capital de Eslovaquia?",
    options: ["Bratislava", "Tirana", "Hanói", "Yaundé"],
    correctIndex: 0,
  },
  {
    id: 20,
    question: "¿Cuál es la capital de Eslovenia?",
    options: ["Bogotá", "Tegucigalpa", "Liubliana", "Kuala Lumpur"],
    correctIndex: 2,
  },
  {
    id: 21,
    question: "¿Cuál es la capital de Croacia?",
    options: ["Estocolmo", "Kampala", "Bruselas", "Zagreb"],
    correctIndex: 3,
  },
  {
    id: 22,
    question: "¿Cuál es la capital de Serbia?",
    options: ["Riad", "Lima", "Bakú", "Belgrado"],
    correctIndex: 3,
  },
  {
    id: 23,
    question: "¿Cuál es la capital de Rumanía?",
    options: ["Riad", "Bucarest", "Nueva Delhi", "Brasilia"],
    correctIndex: 1,
  },
  {
    id: 24,
    question: "¿Cuál es la capital de Bulgaria?",
    options: ["Sofía", "Bakú", "Helsinki", "Sri Jayawardenepura Kotte"],
    correctIndex: 0,
  },
  {
    id: 25,
    question: "¿Cuál es la capital de Ucrania?",
    options: ["Nairobi", "Kiev", "Santiago", "Helsinki"],
    correctIndex: 1,
  },
  {
    id: 26,
    question: "¿Cuál es la capital de Islandia?",
    options: ["Tokio", "Reikiavik", "Argel", "Sri Jayawardenepura Kotte"],
    correctIndex: 1,
  },
  {
    id: 27,
    question: "¿Cuál es la capital de Estonia?",
    options: ["Abuya", "Ankara", "Tallin", "Amán"],
    correctIndex: 2,
  },
  {
    id: 28,
    question: "¿Cuál es la capital de Letonia?",
    options: ["Daca", "Dodoma", "Zagreb", "Riga"],
    correctIndex: 3,
  },
  {
    id: 29,
    question: "¿Cuál es la capital de Lituania?",
    options: ["Helsinki", "Vilna", "Canberra", "Berlín"],
    correctIndex: 1,
  },
  {
    id: 30,
    question: "¿Cuál es la capital de Luxemburgo?",
    options: ["Nicosia", "Ámsterdam", "Manila", "Luxemburgo"],
    correctIndex: 3,
  },
  {
    id: 31,
    question: "¿Cuál es la capital de Malta?",
    options: ["Dodoma", "Islamabad", "La Valeta", "Berna"],
    correctIndex: 2,
  },
  {
    id: 32,
    question: "¿Cuál es la capital de Chipre?",
    options: ["Bangkok", "Belgrado", "Nicosia", "Argel"],
    correctIndex: 2,
  },
  {
    id: 33,
    question: "¿Cuál es la capital de Albania?",
    options: ["Tirana", "Bogotá", "Katmandú", "Acra"],
    correctIndex: 0,
  },
  {
    id: 34,
    question: "¿Cuál es la capital de Marruecos?",
    options: ["Nicosia", "Vilna", "Varsovia", "Rabat"],
    correctIndex: 3,
  },
  {
    id: 35,
    question: "¿Cuál es la capital de Argelia?",
    options: ["Luxemburgo", "Bangkok", "Argel", "Singapur"],
    correctIndex: 2,
  },
  {
    id: 36,
    question: "¿Cuál es la capital de Túnez?",
    options: ["Ámsterdam", "Amán", "Túnez", "Ulán Bator"],
    correctIndex: 2,
  },
  {
    id: 37,
    question: "¿Cuál es la capital de Egipto?",
    options: ["El Cairo", "Viena", "Pekín", "Luanda"],
    correctIndex: 0,
  },
  {
    id: 38,
    question: "¿Cuál es la capital de Sudáfrica?",
    options: ["Daca", "Riga", "Pretoria", "Budapest"],
    correctIndex: 2,
  },
  {
    id: 39,
    question: "¿Cuál es la capital de Kenia?",
    options: ["Oslo", "Caracas", "Kiev", "Nairobi"],
    correctIndex: 3,
  },
  {
    id: 40,
    question: "¿Cuál es la capital de Nigeria?",
    options: ["Ciudad de Guatemala", "Abuya", "Lima", "Caracas"],
    correctIndex: 1,
  },
  {
    id: 41,
    question: "¿Cuál es la capital de Ghana?",
    options: ["Bagdad", "Ereván", "Teherán", "Acra"],
    correctIndex: 3,
  },
  {
    id: 42,
    question: "¿Cuál es la capital de Senegal?",
    options: ["Copenhague", "Maputo", "Dakar", "Malé"],
    correctIndex: 2,
  },
  {
    id: 43,
    question: "¿Cuál es la capital de Etiopía?",
    options: ["Montevideo", "Islamabad", "Adís Abeba", "Praga"],
    correctIndex: 2,
  },
  {
    id: 44,
    question: "¿Cuál es la capital de Angola?",
    options: ["Brasilia", "Luanda", "Nicosia", "Viena"],
    correctIndex: 1,
  },
  {
    id: 45,
    question: "¿Cuál es la capital de Mozambique?",
    options: ["Bruselas", "Bagdad", "Daca", "Maputo"],
    correctIndex: 3,
  },
  {
    id: 46,
    question: "¿Cuál es la capital de México?",
    options: ["Caracas", "Belgrado", "Ciudad de México", "Canberra"],
    correctIndex: 2,
  },
  {
    id: 47,
    question: "¿Cuál es la capital de Guatemala?",
    options: ["Ciudad de Panamá", "Belgrado", "Ámsterdam", "Ciudad de Guatemala"],
    correctIndex: 3,
  },
  {
    id: 48,
    question: "¿Cuál es la capital de Honduras?",
    options: ["Asunción", "El Cairo", "Tegucigalpa", "Lima"],
    correctIndex: 2,
  },
  {
    id: 49,
    question: "¿Cuál es la capital de Costa Rica?",
    options: ["Ámsterdam", "Pretoria", "Riga", "San José"],
    correctIndex: 3,
  },
  {
    id: 50,
    question: "¿Cuál es la capital de Panamá?",
    options: ["Ámsterdam", "Ciudad de Panamá", "Bruselas", "Kuala Lumpur"],
    correctIndex: 1,
  },
  {
    id: 51,
    question: "¿Cuál es la capital de Cuba?",
    options: ["Atenas", "Pekín", "La Habana", "Ámsterdam"],
    correctIndex: 2,
  },
  {
    id: 52,
    question: "¿Cuál es la capital de República Dominicana?",
    options: ["Ereván", "Bogotá", "La Valeta", "Santo Domingo"],
    correctIndex: 3,
  },
  {
    id: 53,
    question: "¿Cuál es la capital de Colombia?",
    options: ["Dublín", "Riad", "Kuala Lumpur", "Bogotá"],
    correctIndex: 3,
  },
  {
    id: 54,
    question: "¿Cuál es la capital de Venezuela?",
    options: ["Tiflis", "Rabat", "Caracas", "Tallin"],
    correctIndex: 2,
  },
  {
    id: 55,
    question: "¿Cuál es la capital de Ecuador?",
    options: ["Quito", "Tiflis", "La Habana", "Budapest"],
    correctIndex: 0,
  },
  {
    id: 56,
    question: "¿Cuál es la capital de Perú?",
    options: ["Kampala", "Lima", "Viena", "Roma"],
    correctIndex: 1,
  },
  {
    id: 57,
    question: "¿Cuál es la capital de Chile?",
    options: ["Riga", "Viena", "Santiago", "Islamabad"],
    correctIndex: 2,
  },
  {
    id: 58,
    question: "¿Cuál es la capital de Argentina?",
    options: ["Tegucigalpa", "Berna", "Buenos Aires", "Nicosia"],
    correctIndex: 2,
  },
  {
    id: 59,
    question: "¿Cuál es la capital de Uruguay?",
    options: ["Nairobi", "Daca", "Ulán Bator", "Montevideo"],
    correctIndex: 3,
  },
  {
    id: 60,
    question: "¿Cuál es la capital de Paraguay?",
    options: ["Moscú", "Praga", "Asunción", "Copenhague"],
    correctIndex: 2,
  },
  {
    id: 61,
    question: "¿Cuál es la capital de Brasil?",
    options: ["Liubliana", "Brasilia", "Yaundé", "Bangkok"],
    correctIndex: 1,
  },
  {
    id: 62,
    question: "¿Cuál es la capital de Canadá?",
    options: ["Ottawa", "Katmandú", "Tallin", "Luanda"],
    correctIndex: 0,
  },
  {
    id: 63,
    question: "¿Cuál es la capital de Estados Unidos?",
    options: ["Bruselas", "Washington D. C.", "Tirana", "Estocolmo"],
    correctIndex: 1,
  },
  {
    id: 64,
    question: "¿Cuál es la capital de Australia?",
    options: ["Canberra", "Lusaka", "Adís Abeba", "París"],
    correctIndex: 0,
  },
  {
    id: 65,
    question: "¿Cuál es la capital de Nueva Zelanda?",
    options: ["Zagreb", "Wellington", "Antananarivo", "Santiago"],
    correctIndex: 1,
  },
  {
    id: 66,
    question: "¿Cuál es la capital de Japón?",
    options: ["Astaná", "Tokio", "Viena", "Helsinki"],
    correctIndex: 1,
  },
  {
    id: 67,
    question: "¿Cuál es la capital de China?",
    options: ["Kuala Lumpur", "Pekín", "Bangkok", "Tegucigalpa"],
    correctIndex: 1,
  },
  {
    id: 68,
    question: "¿Cuál es la capital de Corea del Sur?",
    options: ["Abuya", "Ciudad de Guatemala", "Dublín", "Seúl"],
    correctIndex: 3,
  },
  {
    id: 69,
    question: "¿Cuál es la capital de India?",
    options: ["Tiflis", "Nicosia", "Bakú", "Nueva Delhi"],
    correctIndex: 3,
  },
  {
    id: 70,
    question: "¿Cuál es la capital de Pakistán?",
    options: ["Liubliana", "Yaundé", "Islamabad", "Jerusalén"],
    correctIndex: 2,
  },
  {
    id: 71,
    question: "¿Cuál es la capital de Bangladés?",
    options: ["Bucarest", "Daca", "Bogotá", "Lisboa"],
    correctIndex: 1,
  },
  {
    id: 72,
    question: "¿Cuál es la capital de Tailandia?",
    options: ["Zagreb", "Taskent", "Argel", "Bangkok"],
    correctIndex: 3,
  },
  {
    id: 73,
    question: "¿Cuál es la capital de Vietnam?",
    options: ["Hanói", "Vilna", "Brasilia", "Reikiavik"],
    correctIndex: 0,
  },
  {
    id: 74,
    question: "¿Cuál es la capital de Filipinas?",
    options: ["Manila", "Vilna", "Lisboa", "Luxemburgo"],
    correctIndex: 0,
  },
  {
    id: 75,
    question: "¿Cuál es la capital de Indonesia?",
    options: ["Yakarta", "Lusaka", "Túnez", "Berna"],
    correctIndex: 0,
  },
  {
    id: 76,
    question: "¿Cuál es la capital de Malasia?",
    options: ["Nueva Delhi", "Ereván", "Adís Abeba", "Kuala Lumpur"],
    correctIndex: 3,
  },
  {
    id: 77,
    question: "¿Cuál es la capital de Singapur?",
    options: ["Yakarta", "Bucarest", "Rabat", "Singapur"],
    correctIndex: 3,
  },
  {
    id: 78,
    question: "¿Cuál es la capital de Arabia Saudí?",
    options: ["Maputo", "Riad", "Malé", "Acra"],
    correctIndex: 1,
  },
  {
    id: 79,
    question: "¿Cuál es la capital de Emiratos Árabes Unidos?",
    options: ["Kiev", "Ciudad de Panamá", "Abu Dabi", "Manila"],
    correctIndex: 2,
  },
  {
    id: 80,
    question: "¿Cuál es la capital de Catar?",
    options: ["Doha", "Pekín", "Nueva Delhi", "París"],
    correctIndex: 0,
  },
  {
    id: 81,
    question: "¿Cuál es la capital de Israel?",
    options: ["Berna", "Jerusalén", "Adís Abeba", "Tiflis"],
    correctIndex: 1,
  },
  {
    id: 82,
    question: "¿Cuál es la capital de Jordania?",
    options: ["Amán", "Sri Jayawardenepura Kotte", "Wellington", "Nairobi"],
    correctIndex: 0,
  },
  {
    id: 83,
    question: "¿Cuál es la capital de Turquía?",
    options: ["Dakar", "Ankara", "Taskent", "Santo Domingo"],
    correctIndex: 1,
  },
  {
    id: 84,
    question: "¿Cuál es la capital de Irán?",
    options: ["Kiev", "Teherán", "Caracas", "Tiflis"],
    correctIndex: 1,
  },
  {
    id: 85,
    question: "¿Cuál es la capital de Irak?",
    options: ["Abu Dabi", "Bagdad", "Hanói", "Nairobi"],
    correctIndex: 1,
  },
  {
    id: 86,
    question: "¿Cuál es la capital de Rusia?",
    options: ["Moscú", "Nairobi", "El Cairo", "Tallin"],
    correctIndex: 0,
  },
  {
    id: 87,
    question: "¿Cuál es la capital de Georgia?",
    options: ["Tiflis", "Ereván", "Santiago", "Asunción"],
    correctIndex: 0,
  },
  {
    id: 88,
    question: "¿Cuál es la capital de Armenia?",
    options: ["Bagdad", "Belgrado", "Antananarivo", "Ereván"],
    correctIndex: 3,
  },
  {
    id: 89,
    question: "¿Cuál es la capital de Azerbaiyán?",
    options: ["Estocolmo", "La Valeta", "Bakú", "Kampala"],
    correctIndex: 2,
  },
  {
    id: 90,
    question: "¿Cuál es la capital de Kazajistán?",
    options: ["Lisboa", "Astaná", "Dublín", "Bratislava"],
    correctIndex: 1,
  },
  {
    id: 91,
    question: "¿Cuál es la capital de Uzbekistán?",
    options: ["Taskent", "Jerusalén", "Caracas", "Montevideo"],
    correctIndex: 0,
  },
  {
    id: 92,
    question: "¿Cuál es la capital de Mongolia?",
    options: ["Nicosia", "Ulán Bator", "Santo Domingo", "Canberra"],
    correctIndex: 1,
  },
  {
    id: 93,
    question: "¿Cuál es la capital de Nepal?",
    options: ["Kampala", "Lusaka", "Katmandú", "Copenhague"],
    correctIndex: 2,
  },
  {
    id: 94,
    question: "¿Cuál es la capital de Sri Lanka?",
    options: ["Astaná", "Asunción", "Pekín", "Sri Jayawardenepura Kotte"],
    correctIndex: 3,
  },
  {
    id: 95,
    question: "¿Cuál es la capital de Maldivas?",
    options: ["Malé", "Varsovia", "Montevideo", "Praga"],
    correctIndex: 0,
  },
  {
    id: 96,
    question: "¿Cuál es la capital de Madagascar?",
    options: ["Antananarivo", "Kampala", "Santiago", "Abu Dabi"],
    correctIndex: 0,
  },
  {
    id: 97,
    question: "¿Cuál es la capital de Camerún?",
    options: ["Antananarivo", "Yaundé", "Zagreb", "Brasilia"],
    correctIndex: 1,
  },
  {
    id: 98,
    question: "¿Cuál es la capital de Uganda?",
    options: ["Amán", "Kampala", "Túnez", "Lusaka"],
    correctIndex: 1,
  },
  {
    id: 99,
    question: "¿Cuál es la capital de Tanzania?",
    options: ["Viena", "Túnez", "Dodoma", "Santiago"],
    correctIndex: 2,
  },
  {
    id: 100,
    question: "¿Cuál es la capital de Zambia?",
    options: ["Adís Abeba", "Acra", "Islamabad", "Lusaka"],
    correctIndex: 3,
  },
  {
    id: 101,
    question: "¿Cuál es el resultado de 8 + 3?",
    options: ["10", "11", "13", "12"],
    correctIndex: 1,
  },
  {
    id: 102,
    question: "¿Cuál es el resultado de 8 + 4?",
    options: ["11", "14", "12", "13"],
    correctIndex: 2,
  },
  {
    id: 103,
    question: "¿Cuál es el resultado de 8 + 5?",
    options: ["13", "12", "14", "15"],
    correctIndex: 0,
  },
  {
    id: 104,
    question: "¿Cuál es el resultado de 8 + 6?",
    options: ["15", "13", "14", "16"],
    correctIndex: 2,
  },
  {
    id: 105,
    question: "¿Cuál es el resultado de 8 + 7?",
    options: ["14", "15", "16", "17"],
    correctIndex: 1,
  },
  {
    id: 106,
    question: "¿Cuál es el resultado de 8 + 8?",
    options: ["15", "16", "17", "18"],
    correctIndex: 1,
  },
  {
    id: 107,
    question: "¿Cuál es el resultado de 8 + 9?",
    options: ["17", "19", "18", "16"],
    correctIndex: 0,
  },
  {
    id: 108,
    question: "¿Cuál es el resultado de 8 + 10?",
    options: ["19", "18", "17", "20"],
    correctIndex: 1,
  },
  {
    id: 109,
    question: "¿Cuál es el resultado de 8 + 11?",
    options: ["18", "20", "19", "21"],
    correctIndex: 2,
  },
  {
    id: 110,
    question: "¿Cuál es el resultado de 8 + 12?",
    options: ["19", "20", "21", "22"],
    correctIndex: 1,
  },
  {
    id: 111,
    question: "¿Cuál es el resultado de 9 + 3?",
    options: ["12", "11", "13", "14"],
    correctIndex: 0,
  },
  {
    id: 112,
    question: "¿Cuál es el resultado de 9 + 4?",
    options: ["12", "13", "15", "14"],
    correctIndex: 1,
  },
  {
    id: 113,
    question: "¿Cuál es el resultado de 9 + 5?",
    options: ["13", "16", "15", "14"],
    correctIndex: 3,
  },
  {
    id: 114,
    question: "¿Cuál es el resultado de 9 + 6?",
    options: ["17", "16", "14", "15"],
    correctIndex: 3,
  },
  {
    id: 115,
    question: "¿Cuál es el resultado de 9 + 7?",
    options: ["15", "16", "18", "17"],
    correctIndex: 1,
  },
  {
    id: 116,
    question: "¿Cuál es el resultado de 9 + 8?",
    options: ["19", "16", "18", "17"],
    correctIndex: 3,
  },
  {
    id: 117,
    question: "¿Cuál es el resultado de 9 + 9?",
    options: ["20", "19", "18", "17"],
    correctIndex: 2,
  },
  {
    id: 118,
    question: "¿Cuál es el resultado de 9 + 10?",
    options: ["19", "21", "20", "18"],
    correctIndex: 0,
  },
  {
    id: 119,
    question: "¿Cuál es el resultado de 9 + 11?",
    options: ["20", "22", "21", "19"],
    correctIndex: 0,
  },
  {
    id: 120,
    question: "¿Cuál es el resultado de 9 + 12?",
    options: ["20", "23", "22", "21"],
    correctIndex: 3,
  },
  {
    id: 121,
    question: "¿Cuál es el resultado de 10 + 3?",
    options: ["12", "15", "14", "13"],
    correctIndex: 3,
  },
  {
    id: 122,
    question: "¿Cuál es el resultado de 10 + 4?",
    options: ["15", "16", "13", "14"],
    correctIndex: 3,
  },
  {
    id: 123,
    question: "¿Cuál es el resultado de 10 + 5?",
    options: ["16", "14", "17", "15"],
    correctIndex: 3,
  },
  {
    id: 124,
    question: "¿Cuál es el resultado de 10 + 6?",
    options: ["17", "18", "15", "16"],
    correctIndex: 3,
  },
  {
    id: 125,
    question: "¿Cuál es el resultado de 10 + 7?",
    options: ["16", "19", "17", "18"],
    correctIndex: 2,
  },
  {
    id: 126,
    question: "¿Cuál es el resultado de 10 + 8?",
    options: ["19", "20", "17", "18"],
    correctIndex: 3,
  },
  {
    id: 127,
    question: "¿Cuál es el resultado de 10 + 9?",
    options: ["19", "20", "18", "21"],
    correctIndex: 0,
  },
  {
    id: 128,
    question: "¿Cuál es el resultado de 10 + 10?",
    options: ["21", "22", "20", "19"],
    correctIndex: 2,
  },
  {
    id: 129,
    question: "¿Cuál es el resultado de 10 + 11?",
    options: ["20", "21", "23", "22"],
    correctIndex: 1,
  },
  {
    id: 130,
    question: "¿Cuál es el resultado de 10 + 12?",
    options: ["24", "21", "23", "22"],
    correctIndex: 3,
  },
  {
    id: 131,
    question: "¿Cuál es el resultado de 11 + 3?",
    options: ["15", "14", "13", "16"],
    correctIndex: 1,
  },
  {
    id: 132,
    question: "¿Cuál es el resultado de 11 + 4?",
    options: ["16", "17", "14", "15"],
    correctIndex: 3,
  },
  {
    id: 133,
    question: "¿Cuál es el resultado de 11 + 5?",
    options: ["18", "17", "15", "16"],
    correctIndex: 3,
  },
  {
    id: 134,
    question: "¿Cuál es el resultado de 11 + 6?",
    options: ["18", "19", "16", "17"],
    correctIndex: 3,
  },
  {
    id: 135,
    question: "¿Cuál es el resultado de 11 + 7?",
    options: ["18", "19", "20", "17"],
    correctIndex: 0,
  },
  {
    id: 136,
    question: "¿Cuál es el resultado de 11 + 8?",
    options: ["21", "20", "19", "18"],
    correctIndex: 2,
  },
  {
    id: 137,
    question: "¿Cuál es el resultado de 11 + 9?",
    options: ["22", "19", "21", "20"],
    correctIndex: 3,
  },
  {
    id: 138,
    question: "¿Cuál es el resultado de 11 + 10?",
    options: ["23", "20", "22", "21"],
    correctIndex: 3,
  },
  {
    id: 139,
    question: "¿Cuál es el resultado de 11 + 11?",
    options: ["23", "22", "21", "24"],
    correctIndex: 1,
  },
  {
    id: 140,
    question: "¿Cuál es el resultado de 11 + 12?",
    options: ["22", "24", "23", "25"],
    correctIndex: 2,
  },
  {
    id: 141,
    question: "¿Cuál es el resultado de 6 x 4?",
    options: ["24", "20", "30", "34"],
    correctIndex: 0,
  },
  {
    id: 142,
    question: "¿Cuál es el resultado de 6 x 5?",
    options: ["40", "30", "36", "25"],
    correctIndex: 1,
  },
  {
    id: 143,
    question: "¿Cuál es el resultado de 6 x 6?",
    options: ["46", "30", "42", "36"],
    correctIndex: 3,
  },
  {
    id: 144,
    question: "¿Cuál es el resultado de 6 x 7?",
    options: ["42", "35", "52", "48"],
    correctIndex: 0,
  },
  {
    id: 145,
    question: "¿Cuál es el resultado de 6 x 8?",
    options: ["58", "54", "48", "40"],
    correctIndex: 2,
  },
  {
    id: 146,
    question: "¿Cuál es el resultado de 6 x 9?",
    options: ["64", "60", "54", "45"],
    correctIndex: 2,
  },
  {
    id: 147,
    question: "¿Cuál es el resultado de 6 x 10?",
    options: ["60", "50", "70", "66"],
    correctIndex: 0,
  },
  {
    id: 148,
    question: "¿Cuál es el resultado de 6 x 11?",
    options: ["66", "76", "72", "55"],
    correctIndex: 0,
  },
  {
    id: 149,
    question: "¿Cuál es el resultado de 6 x 12?",
    options: ["78", "82", "60", "72"],
    correctIndex: 3,
  },
  {
    id: 150,
    question: "¿Cuál es el resultado de 6 x 13?",
    options: ["65", "84", "88", "78"],
    correctIndex: 3,
  },
  {
    id: 151,
    question: "¿Cuál es el resultado de 7 x 4?",
    options: ["35", "28", "24", "38"],
    correctIndex: 1,
  },
  {
    id: 152,
    question: "¿Cuál es el resultado de 7 x 5?",
    options: ["35", "42", "30", "45"],
    correctIndex: 0,
  },
  {
    id: 153,
    question: "¿Cuál es el resultado de 7 x 6?",
    options: ["49", "36", "42", "52"],
    correctIndex: 2,
  },
  {
    id: 154,
    question: "¿Cuál es el resultado de 7 x 7?",
    options: ["59", "56", "49", "42"],
    correctIndex: 2,
  },
  {
    id: 155,
    question: "¿Cuál es el resultado de 7 x 8?",
    options: ["56", "48", "66", "63"],
    correctIndex: 0,
  },
  {
    id: 156,
    question: "¿Cuál es el resultado de 7 x 9?",
    options: ["63", "70", "54", "73"],
    correctIndex: 0,
  },
  {
    id: 157,
    question: "¿Cuál es el resultado de 7 x 10?",
    options: ["70", "77", "60", "80"],
    correctIndex: 0,
  },
  {
    id: 158,
    question: "¿Cuál es el resultado de 7 x 11?",
    options: ["77", "84", "87", "66"],
    correctIndex: 0,
  },
  {
    id: 159,
    question: "¿Cuál es el resultado de 7 x 12?",
    options: ["84", "94", "91", "72"],
    correctIndex: 0,
  },
  {
    id: 160,
    question: "¿Cuál es el resultado de 7 x 13?",
    options: ["101", "78", "91", "98"],
    correctIndex: 2,
  },
  {
    id: 161,
    question: "¿Cuál es el resultado de 8 x 4?",
    options: ["40", "42", "32", "28"],
    correctIndex: 2,
  },
  {
    id: 162,
    question: "¿Cuál es el resultado de 8 x 5?",
    options: ["35", "50", "40", "48"],
    correctIndex: 2,
  },
  {
    id: 163,
    question: "¿Cuál es el resultado de 8 x 6?",
    options: ["48", "56", "58", "42"],
    correctIndex: 0,
  },
  {
    id: 164,
    question: "¿Cuál es el resultado de 8 x 7?",
    options: ["49", "64", "66", "56"],
    correctIndex: 3,
  },
  {
    id: 165,
    question: "¿Cuál es el resultado de 8 x 8?",
    options: ["56", "64", "74", "72"],
    correctIndex: 1,
  },
  {
    id: 166,
    question: "¿Cuál es el resultado de 8 x 9?",
    options: ["80", "82", "72", "63"],
    correctIndex: 2,
  },
  {
    id: 167,
    question: "¿Cuál es el resultado de 8 x 10?",
    options: ["88", "90", "80", "70"],
    correctIndex: 2,
  },
  {
    id: 168,
    question: "¿Cuál es el resultado de 8 x 11?",
    options: ["96", "88", "98", "77"],
    correctIndex: 1,
  },
  {
    id: 169,
    question: "¿Cuál es el resultado de 8 x 12?",
    options: ["104", "84", "96", "106"],
    correctIndex: 2,
  },
  {
    id: 170,
    question: "¿Cuál es el resultado de 8 x 13?",
    options: ["104", "114", "112", "91"],
    correctIndex: 0,
  },
  {
    id: 171,
    question: "¿Cuál es el resultado de 9 x 4?",
    options: ["32", "36", "45", "46"],
    correctIndex: 1,
  },
  {
    id: 172,
    question: "¿Cuál es el resultado de 9 x 5?",
    options: ["55", "40", "54", "45"],
    correctIndex: 3,
  },
  {
    id: 173,
    question: "¿Cuál es el resultado de 9 x 6?",
    options: ["48", "63", "64", "54"],
    correctIndex: 3,
  },
  {
    id: 174,
    question: "¿Cuál es el resultado de 9 x 7?",
    options: ["72", "56", "63", "73"],
    correctIndex: 2,
  },
  {
    id: 175,
    question: "¿Cuál es el resultado de 9 x 8?",
    options: ["64", "82", "72", "81"],
    correctIndex: 2,
  },
  {
    id: 176,
    question: "¿Cuál es el resultado de 9 x 9?",
    options: ["90", "72", "91", "81"],
    correctIndex: 3,
  },
  {
    id: 177,
    question: "¿Cuál es el resultado de 9 x 10?",
    options: ["99", "90", "80", "100"],
    correctIndex: 1,
  },
  {
    id: 178,
    question: "¿Cuál es el resultado de 9 x 11?",
    options: ["99", "88", "108", "109"],
    correctIndex: 0,
  },
  {
    id: 179,
    question: "¿Cuál es el resultado de 9 x 12?",
    options: ["108", "117", "118", "96"],
    correctIndex: 0,
  },
  {
    id: 180,
    question: "¿Cuál es el resultado de 9 x 13?",
    options: ["126", "117", "127", "104"],
    correctIndex: 1,
  },
  {
    id: 181,
    question: "¿Cuál es el resultado de 24 ÷ 3?",
    options: ["9", "7", "10", "8"],
    correctIndex: 3,
  },
  {
    id: 182,
    question: "¿Cuál es el resultado de 27 ÷ 3?",
    options: ["10", "9", "11", "8"],
    correctIndex: 1,
  },
  {
    id: 183,
    question: "¿Cuál es el resultado de 30 ÷ 3?",
    options: ["12", "9", "10", "11"],
    correctIndex: 2,
  },
  {
    id: 184,
    question: "¿Cuál es el resultado de 33 ÷ 3?",
    options: ["12", "10", "13", "11"],
    correctIndex: 3,
  },
  {
    id: 185,
    question: "¿Cuál es el resultado de 36 ÷ 3?",
    options: ["12", "11", "13", "14"],
    correctIndex: 0,
  },
  {
    id: 186,
    question: "¿Cuál es el resultado de 39 ÷ 3?",
    options: ["14", "15", "13", "12"],
    correctIndex: 2,
  },
  {
    id: 187,
    question: "¿Cuál es el resultado de 42 ÷ 3?",
    options: ["14", "15", "16", "13"],
    correctIndex: 0,
  },
  {
    id: 188,
    question: "¿Cuál es el resultado de 45 ÷ 3?",
    options: ["16", "14", "15", "17"],
    correctIndex: 2,
  },
  {
    id: 189,
    question: "¿Cuál es el resultado de 48 ÷ 3?",
    options: ["17", "16", "18", "15"],
    correctIndex: 1,
  },
  {
    id: 190,
    question: "¿Cuál es el resultado de 51 ÷ 3?",
    options: ["18", "16", "17", "19"],
    correctIndex: 2,
  },
  {
    id: 191,
    question: "¿Cuál es el resultado de 32 ÷ 4?",
    options: ["7", "8", "10", "9"],
    correctIndex: 1,
  },
  {
    id: 192,
    question: "¿Cuál es el resultado de 36 ÷ 4?",
    options: ["10", "8", "11", "9"],
    correctIndex: 3,
  },
  {
    id: 193,
    question: "¿Cuál es el resultado de 40 ÷ 4?",
    options: ["10", "11", "12", "9"],
    correctIndex: 0,
  },
  {
    id: 194,
    question: "¿Cuál es el resultado de 44 ÷ 4?",
    options: ["10", "12", "11", "13"],
    correctIndex: 2,
  },
  {
    id: 195,
    question: "¿Cuál es el resultado de 48 ÷ 4?",
    options: ["12", "13", "14", "11"],
    correctIndex: 0,
  },
  {
    id: 196,
    question: "¿Cuál es el resultado de 52 ÷ 4?",
    options: ["13", "14", "15", "12"],
    correctIndex: 0,
  },
  {
    id: 197,
    question: "¿Cuál es el resultado de 56 ÷ 4?",
    options: ["15", "13", "14", "16"],
    correctIndex: 2,
  },
  {
    id: 198,
    question: "¿Cuál es el resultado de 60 ÷ 4?",
    options: ["15", "16", "14", "17"],
    correctIndex: 0,
  },
  {
    id: 199,
    question: "¿Cuál es el resultado de 64 ÷ 4?",
    options: ["17", "18", "16", "15"],
    correctIndex: 2,
  },
  {
    id: 200,
    question: "¿Cuál es el resultado de 68 ÷ 4?",
    options: ["19", "17", "16", "18"],
    correctIndex: 1,
  },
  {
    id: 201,
    question: "¿Qué planeta es conocido como el planeta rojo?",
    options: ["Venus", "Marte", "Saturno", "Júpiter"],
    correctIndex: 1,
  },
  {
    id: 202,
    question: "¿Cuál es el planeta más grande del sistema solar?",
    options: ["Júpiter", "Neptuno", "Tierra", "Saturno"],
    correctIndex: 0,
  },
  {
    id: 203,
    question: "¿Cuál es el planeta más cercano al Sol?",
    options: ["Tierra", "Venus", "Mercurio", "Marte"],
    correctIndex: 2,
  },
  {
    id: 204,
    question: "¿Qué astro es el centro del sistema solar?",
    options: ["Marte", "La Luna", "El Sol", "Júpiter"],
    correctIndex: 2,
  },
  {
    id: 205,
    question: "¿Qué gas necesitan principalmente los humanos para respirar?",
    options: ["Oxígeno", "Dióxido de carbono", "Helio", "Hidrógeno"],
    correctIndex: 0,
  },
  {
    id: 206,
    question: "¿Cuál es el gas más abundante en la atmósfera terrestre?",
    options: ["Oxígeno", "Nitrógeno", "Argón", "Helio"],
    correctIndex: 1,
  },
  {
    id: 207,
    question: "¿Qué órgano bombea la sangre?",
    options: ["Corazón", "Hígado", "Riñón", "Pulmón"],
    correctIndex: 0,
  },
  {
    id: 208,
    question: "¿Qué órgano se encarga principalmente de pensar y coordinar el cuerpo?",
    options: ["Cerebro", "Pulmón", "Estómago", "Páncreas"],
    correctIndex: 0,
  },
  {
    id: 209,
    question: "¿Cuántos huesos tiene aproximadamente un adulto humano?",
    options: ["300", "98", "150", "206"],
    correctIndex: 3,
  },
  {
    id: 210,
    question: "¿Qué parte de la planta absorbe agua del suelo?",
    options: ["Raíz", "Hoja", "Flor", "Tallo"],
    correctIndex: 0,
  },
  {
    id: 211,
    question: "¿Qué proceso usan las plantas para fabricar alimento con luz?",
    options: ["Digestión", "Evaporación", "Respiración", "Fotosíntesis"],
    correctIndex: 3,
  },
  {
    id: 212,
    question: "¿Qué molécula almacena la información genética?",
    options: ["Glucosa", "ADN", "ARNm", "Hemoglobina"],
    correctIndex: 1,
  },
  {
    id: 213,
    question: "¿Cuál es el símbolo químico del agua?",
    options: ["H2O", "NaCl", "O2", "CO2"],
    correctIndex: 0,
  },
  {
    id: 214,
    question: "¿Cuál es el símbolo químico del oxígeno?",
    options: ["O", "Ox", "Og", "Om"],
    correctIndex: 0,
  },
  {
    id: 215,
    question: "¿Cuál es el símbolo químico del oro?",
    options: ["Fe", "Ag", "Or", "Au"],
    correctIndex: 3,
  },
  {
    id: 216,
    question: "¿Cuál es el símbolo químico de la plata?",
    options: ["Ag", "Pt", "Pb", "Au"],
    correctIndex: 0,
  },
  {
    id: 217,
    question: "¿Cuál es el símbolo químico del hierro?",
    options: ["H", "Ir", "Fe", "He"],
    correctIndex: 2,
  },
  {
    id: 218,
    question: "¿Cuál es el símbolo químico del sodio?",
    options: ["Sd", "Na", "S", "So"],
    correctIndex: 1,
  },
  {
    id: 219,
    question: "¿Qué metal líquido se usaba tradicionalmente en termómetros?",
    options: ["Cobre", "Mercurio", "Níquel", "Aluminio"],
    correctIndex: 1,
  },
  {
    id: 220,
    question: "¿Cuál es el metal más ligero?",
    options: ["Hierro", "Oro", "Litio", "Plata"],
    correctIndex: 2,
  },
  {
    id: 221,
    question: "¿Qué instrumento mide la temperatura?",
    options: ["Higrómetro", "Anemómetro", "Barómetro", "Termómetro"],
    correctIndex: 3,
  },
  {
    id: 222,
    question: "¿Qué instrumento mide la presión atmosférica?",
    options: ["Barómetro", "Brújula", "Cronómetro", "Termómetro"],
    correctIndex: 0,
  },
  {
    id: 223,
    question: "¿Qué instrumento indica la dirección norte?",
    options: ["Brújula", "Telescopio", "Microscopio", "Anemómetro"],
    correctIndex: 0,
  },
  {
    id: 224,
    question: "¿Qué instrumento sirve para observar objetos muy pequeños?",
    options: ["Barómetro", "Telescopio", "Microscopio", "Radar"],
    correctIndex: 2,
  },
  {
    id: 225,
    question: "¿Qué instrumento sirve para observar cuerpos celestes lejanos?",
    options: ["Termómetro", "Telescopio", "Sismógrafo", "Microscopio"],
    correctIndex: 1,
  },
  {
    id: 226,
    question: "¿Qué fenómeno produce el sonido?",
    options: ["Magnetismo", "Gravedad", "Vibraciones", "Luz"],
    correctIndex: 2,
  },
  {
    id: 227,
    question: "¿Qué unidad se usa para medir la fuerza en el Sistema Internacional?",
    options: ["Newton", "Pascal", "Julio", "Vatio"],
    correctIndex: 0,
  },
  {
    id: 228,
    question: "¿Qué unidad se usa para medir la energía?",
    options: ["Amperio", "Metro", "Newton", "Julio"],
    correctIndex: 3,
  },
  {
    id: 229,
    question: "¿Qué unidad se usa para medir la potencia?",
    options: ["Ohmio", "Voltio", "Vatio", "Tesla"],
    correctIndex: 2,
  },
  {
    id: 230,
    question: "¿Qué unidad se usa para medir la corriente eléctrica?",
    options: ["Amperio", "Vatio", "Voltio", "Ohmio"],
    correctIndex: 0,
  },
  {
    id: 231,
    question: "¿Qué unidad se usa para medir la resistencia eléctrica?",
    options: ["Ohmio", "Voltio", "Amperio", "Litro"],
    correctIndex: 0,
  },
  {
    id: 232,
    question: "¿Qué fuerza atrae los objetos hacia la Tierra?",
    options: ["Inercia", "Gravedad", "Magnetismo", "Fricción"],
    correctIndex: 1,
  },
  {
    id: 233,
    question: "¿Qué estado de la materia tiene forma y volumen definidos?",
    options: ["Gas", "Líquido", "Sólido", "Plasma"],
    correctIndex: 2,
  },
  {
    id: 234,
    question: "¿Qué estado de la materia no tiene forma ni volumen definidos?",
    options: ["Cristal", "Líquido", "Sólido", "Gas"],
    correctIndex: 3,
  },
  {
    id: 235,
    question: "¿Cómo se llama el paso de líquido a gas?",
    options: ["Fusión", "Evaporación", "Condensación", "Solidificación"],
    correctIndex: 1,
  },
  {
    id: 236,
    question: "¿Cómo se llama el paso de gas a líquido?",
    options: ["Evaporación", "Sublimación", "Condensación", "Fusión"],
    correctIndex: 2,
  },
  {
    id: 237,
    question: "¿Cómo se llama el paso de sólido a líquido?",
    options: ["Evaporación", "Condensación", "Fusión", "Solidificación"],
    correctIndex: 2,
  },
  {
    id: 238,
    question: "¿Cómo se llama el paso de líquido a sólido?",
    options: ["Sublimación", "Fusión", "Evaporación", "Solidificación"],
    correctIndex: 3,
  },
  {
    id: 239,
    question: "¿Cuál es la estrella más cercana a la Tierra?",
    options: ["Sirio", "Betelgeuse", "Polaris", "El Sol"],
    correctIndex: 3,
  },
  {
    id: 240,
    question: "¿Qué satélite natural orbita la Tierra?",
    options: ["Fobos", "La Luna", "Europa", "Titán"],
    correctIndex: 1,
  },
  {
    id: 241,
    question: "¿Cuántos planetas hay en el sistema solar?",
    options: ["10", "9", "7", "8"],
    correctIndex: 3,
  },
  {
    id: 242,
    question: "¿Qué planeta tiene anillos muy visibles?",
    options: ["Saturno", "Mercurio", "Venus", "Marte"],
    correctIndex: 0,
  },
  {
    id: 243,
    question: "¿Qué océano es el más grande?",
    options: ["Ártico", "Índico", "Atlántico", "Pacífico"],
    correctIndex: 3,
  },
  {
    id: 244,
    question: "¿Qué océano separa Europa y América?",
    options: ["Atlántico", "Pacífico", "Ártico", "Índico"],
    correctIndex: 0,
  },
  {
    id: 245,
    question: "¿Cuál es el continente más grande?",
    options: ["Europa", "Antártida", "Oceanía", "Asia"],
    correctIndex: 3,
  },
  {
    id: 246,
    question: "¿Cuál es el continente más pequeño?",
    options: ["Oceanía", "Europa", "África", "Asia"],
    correctIndex: 0,
  },
  {
    id: 247,
    question: "¿Qué cordillera separa Europa de Asia en parte?",
    options: ["Pirineos", "Urales", "Andes", "Alpes"],
    correctIndex: 1,
  },
  {
    id: 248,
    question: "¿Cuál es la montaña más alta del mundo?",
    options: ["K2", "Kilimanjaro", "Everest", "Mont Blanc"],
    correctIndex: 2,
  },
  {
    id: 249,
    question: "¿Cuál es el río más largo del mundo según muchas mediciones modernas?",
    options: ["Yangtsé", "Nilo", "Amazonas", "Misisipi"],
    correctIndex: 2,
  },
  {
    id: 250,
    question: "¿Qué río pasa por París?",
    options: ["Tíber", "Támesis", "Danubio", "Sena"],
    correctIndex: 3,
  },
  {
    id: 251,
    question: "¿Cuál es el animal terrestre más rápido?",
    options: ["Tigre", "Caballo", "León", "Guepardo"],
    correctIndex: 3,
  },
  {
    id: 252,
    question: "¿Cuál es el mamífero marino más grande?",
    options: ["Foca", "Ballena azul", "Delfín", "Orca"],
    correctIndex: 1,
  },
  {
    id: 253,
    question: "¿Cuál es el ave que no puede volar y vive en la Antártida?",
    options: ["Pingüino", "Gaviota", "Loro", "Águila"],
    correctIndex: 0,
  },
  {
    id: 254,
    question: "¿Cuál es el animal conocido por su trompa?",
    options: ["Hipopótamo", "Rinoceronte", "Elefante", "Jirafa"],
    correctIndex: 2,
  },
  {
    id: 255,
    question: "¿Cuál es el reptil que puede cambiar de color?",
    options: ["Iguana", "Cocodrilo", "Tortuga", "Camaleón"],
    correctIndex: 3,
  },
  {
    id: 256,
    question: "¿Cuál es el animal que produce miel?",
    options: ["Hormiga", "Abeja", "Mosca", "Avispa"],
    correctIndex: 1,
  },
  {
    id: 257,
    question: "¿Cuál es el animal famoso por su cuello largo?",
    options: ["Jirafa", "Elefante", "Gorila", "Cebra"],
    correctIndex: 0,
  },
  {
    id: 258,
    question: "¿Cuál es el animal que construye presas en ríos?",
    options: ["Zorro", "Castor", "Nutria", "Ardilla"],
    correctIndex: 1,
  },
  {
    id: 259,
    question: "¿Cuál es el animal doméstico que maúlla?",
    options: ["Conejo", "Gato", "Perro", "Caballo"],
    correctIndex: 1,
  },
  {
    id: 260,
    question: "¿Cuál es el animal doméstico que ladra?",
    options: ["Oveja", "Vaca", "Gato", "Perro"],
    correctIndex: 3,
  },
  {
    id: 261,
    question: "¿Cuál es el ave símbolo de la paz?",
    options: ["Paloma", "Cuervo", "Pavo", "Halcón"],
    correctIndex: 0,
  },
  {
    id: 262,
    question: "¿Cuál es el insecto que pasa por metamorfosis y se convierte en mariposa?",
    options: ["Oruga", "Mosquito", "Araña", "Escarabajo"],
    correctIndex: 0,
  },
  {
    id: 263,
    question: "¿Cuál es el animal conocido por sus rayas blancas y negras?",
    options: ["Cebra", "Tigre", "Panda rojo", "Leopardo"],
    correctIndex: 0,
  },
  {
    id: 264,
    question: "¿Cuál es el animal que hiberna con frecuencia en invierno?",
    options: ["Delfín", "Canguro", "Águila", "Oso"],
    correctIndex: 3,
  },
  {
    id: 265,
    question: "¿Cuál es el pez famoso por su memoria popularmente corta?",
    options: ["Pez dorado", "Atún", "Merluza", "Salmón"],
    correctIndex: 0,
  },
  {
    id: 266,
    question: "¿Cuál es el animal que vive en colmenas?",
    options: ["Libélula", "Mariposa", "Abeja", "Saltamontes"],
    correctIndex: 2,
  },
  {
    id: 267,
    question: "¿Cuál es el animal que pone huevos y es mamífero?",
    options: ["Canguro", "Delfín", "Ornitorrinco", "Koala"],
    correctIndex: 2,
  },
  {
    id: 268,
    question: "¿Cuál es el ave corredora más grande?",
    options: ["Cóndor", "Avestruz", "Pingüino", "Cisne"],
    correctIndex: 1,
  },
  {
    id: 269,
    question: "¿Cuál es el marsupial australiano que salta?",
    options: ["Koala", "Dingo", "Canguro", "Emú"],
    correctIndex: 2,
  },
  {
    id: 270,
    question: "¿Cuál es el animal que suele dormir colgado boca abajo?",
    options: ["Ratón", "Murciélago", "Búho", "Ardilla"],
    correctIndex: 1,
  },
  {
    id: 271,
    question: "¿Cuál es el animal conocido por su tinta defensiva?",
    options: ["Medusa", "Caballito de mar", "Cangrejo", "Pulpo"],
    correctIndex: 3,
  },
  {
    id: 272,
    question: "¿Cuál es el animal con ocho patas que no es insecto?",
    options: ["Mosca", "Araña", "Hormiga", "Abeja"],
    correctIndex: 1,
  },
  {
    id: 273,
    question: "¿Cuál es el animal marino con caparazón y pinzas?",
    options: ["Pulpo", "Cangrejo", "Delfín", "Sardina"],
    correctIndex: 1,
  },
  {
    id: 274,
    question: "¿Cuál es el animal que suele vivir en manadas y aúlla?",
    options: ["Ciervo", "Gato", "Zorro", "Lobo"],
    correctIndex: 3,
  },
  {
    id: 275,
    question: "¿Cuál es el animal con cuernos que suele vivir en granjas?",
    options: ["Gallina", "Pato", "Vaca", "Conejo"],
    correctIndex: 2,
  },
  {
    id: 276,
    question: "¿Cuál es el ave de corral que pone huevos?",
    options: ["Gallina", "Ganso macho", "Pavo real", "Pato macho"],
    correctIndex: 0,
  },
  {
    id: 277,
    question: "¿Cuál es el animal que da lana?",
    options: ["Perro", "Cerdo", "Oveja", "Cabra montés"],
    correctIndex: 2,
  },
  {
    id: 278,
    question: "¿Cuál es el animal famoso por su caparazón lento?",
    options: ["Tortuga", "Serpiente", "Rana", "Lagarto"],
    correctIndex: 0,
  },
  {
    id: 279,
    question: "¿Cuál es el anfibio que croa?",
    options: ["Paloma", "Ratón", "Serpiente", "Rana"],
    correctIndex: 3,
  },
  {
    id: 280,
    question: "¿Cuál es el mamífero que vuela?",
    options: ["Ardilla", "Pato", "Murciélago", "Pingüino"],
    correctIndex: 2,
  },
  {
    id: 281,
    question: "¿Cuál es el animal blanco y negro que come bambú?",
    options: ["Oso polar", "Koala", "Panda", "Mapache"],
    correctIndex: 2,
  },
  {
    id: 282,
    question: "¿Cuál es el animal polar de gran tamaño?",
    options: ["Gorila", "Camello", "Panda", "Oso polar"],
    correctIndex: 3,
  },
  {
    id: 283,
    question: "¿Cuál es el animal adaptado al desierto con jorobas?",
    options: ["Camello", "Ciervo", "Caballo", "Búfalo"],
    correctIndex: 0,
  },
  {
    id: 284,
    question: "¿Cuál es el animal marino inteligente que vive en grupos?",
    options: ["Delfín", "Tiburón", "Medusa", "Langosta"],
    correctIndex: 0,
  },
  {
    id: 285,
    question: "¿Cuál es el pez cartilaginoso famoso por sus dientes?",
    options: ["Salmón", "Carpa", "Trucha", "Tiburón"],
    correctIndex: 3,
  },
  {
    id: 286,
    question: "¿Cuál es el animal que se desplaza arrastrándose y puede no tener patas?",
    options: ["Conejo", "Rana", "Serpiente", "Cebra"],
    correctIndex: 2,
  },
  {
    id: 287,
    question: "¿Cuál es el ave nocturna asociada a la sabiduría?",
    options: ["Flamenco", "Búho", "Gallo", "Paloma"],
    correctIndex: 1,
  },
  {
    id: 288,
    question: "¿Cuál es el ave rosa que suele apoyarse en una pata?",
    options: ["Flamenco", "Cuervo", "Pingüino", "Águila"],
    correctIndex: 0,
  },
  {
    id: 289,
    question: "¿Cuál es el animal africano con melena en los machos?",
    options: ["Tigre", "Leopardo", "León", "Hiena"],
    correctIndex: 2,
  },
  {
    id: 290,
    question: "¿Cuál es el animal con manchas y gran velocidad en carrera corta?",
    options: ["Lobo", "Puma", "Oso", "Guepardo"],
    correctIndex: 3,
  },
  {
    id: 291,
    question: "¿Cuál es el animal parecido al caballo con rayas?",
    options: ["Burro", "Antílope", "Cebra", "Llama"],
    correctIndex: 2,
  },
  {
    id: 292,
    question: "¿Cuál es el animal que suele llevar crías en una bolsa?",
    options: ["Oso", "Canguro", "Gato", "Caballo"],
    correctIndex: 1,
  },
  {
    id: 293,
    question: "¿Cuál es el animal marino con tentáculos urticantes?",
    options: ["Medusa", "Delfín", "Tortuga", "Foca"],
    correctIndex: 0,
  },
  {
    id: 294,
    question: "¿Cuál es el animal que cambia de renacuajo a adulto?",
    options: ["Lagarto", "Rana", "Pollo", "Gato"],
    correctIndex: 1,
  },
  {
    id: 295,
    question: "¿Cuál es el animal conocido por su cola de pavo real?",
    options: ["Gallo", "Pavo real", "Cisne", "Águila"],
    correctIndex: 1,
  },
  {
    id: 296,
    question: "¿Cuál es el animal que puede regenerar partes de su cuerpo?",
    options: ["Estrella de mar", "Delfín", "Ballena", "Tiburón"],
    correctIndex: 0,
  },
  {
    id: 297,
    question: "¿Cuál es el animal de granja que suele decirse que gruñe?",
    options: ["Gallina", "Oveja", "Cerdo", "Cabra"],
    correctIndex: 2,
  },
  {
    id: 298,
    question: "¿Cuál es el animal de granja que suele balar?",
    options: ["Oveja", "Caballo", "Gato", "Cerdo"],
    correctIndex: 0,
  },
  {
    id: 299,
    question: "¿Cuál es el animal de granja que relincha?",
    options: ["Perro", "Caballo", "Pato", "Vaca"],
    correctIndex: 1,
  },
  {
    id: 300,
    question: "¿Cuál es el animal de granja que hace 'muuu'?",
    options: ["Vaca", "Oveja", "Gallina", "Cerdo"],
    correctIndex: 0,
  },
  {
    id: 301,
    question: "¿Quién pintó la Mona Lisa?",
    options: ["Dalí", "Picasso", "Van Gogh", "Leonardo da Vinci"],
    correctIndex: 3,
  },
  {
    id: 302,
    question: "¿Quién escribió Don Quijote de la Mancha?",
    options: ["Lope de Vega", "Quevedo", "Miguel de Cervantes", "Federico García Lorca"],
    correctIndex: 2,
  },
  {
    id: 303,
    question: "¿En qué año llegó el hombre a la Luna?",
    options: ["1965", "1959", "1972", "1969"],
    correctIndex: 3,
  },
  {
    id: 304,
    question: "¿Qué país ganó el Mundial de fútbol de 2010?",
    options: ["Alemania", "Brasil", "Argentina", "España"],
    correctIndex: 3,
  },
  {
    id: 305,
    question: "¿Cada cuántos años se celebran normalmente los Juegos Olímpicos de verano?",
    options: ["5", "3", "4", "2"],
    correctIndex: 2,
  },
  {
    id: 306,
    question: "¿Qué deporte se juega en Wimbledon?",
    options: ["Golf", "Baloncesto", "Rugby", "Tenis"],
    correctIndex: 3,
  },
  {
    id: 307,
    question: "¿Cuántos jugadores tiene un equipo de fútbol en el campo?",
    options: ["9", "10", "11", "7"],
    correctIndex: 2,
  },
  {
    id: 308,
    question: "¿Cuántos jugadores tiene un equipo de baloncesto en pista?",
    options: ["11", "5", "7", "6"],
    correctIndex: 1,
  },
  {
    id: 309,
    question: "¿Qué deporte utiliza un bate y una pelota en el diamante?",
    options: ["Balonmano", "Hockey", "Béisbol", "Tenis"],
    correctIndex: 2,
  },
  {
    id: 310,
    question: "¿Qué deporte se practica en una piscina con calles?",
    options: ["Esgrima", "Boxeo", "Natación", "Ciclismo"],
    correctIndex: 2,
  },
  {
    id: 311,
    question: "¿Qué color resulta de mezclar rojo y amarillo?",
    options: ["Verde", "Morado", "Azul", "Naranja"],
    correctIndex: 3,
  },
  {
    id: 312,
    question: "¿Qué color resulta de mezclar azul y amarillo?",
    options: ["Rosa", "Rojo", "Verde", "Naranja"],
    correctIndex: 2,
  },
  {
    id: 313,
    question: "¿Cuántas notas musicales básicas hay en la escala diatónica?",
    options: ["6", "5", "8", "7"],
    correctIndex: 3,
  },
  {
    id: 314,
    question: "¿Qué instrumento tiene teclas blancas y negras?",
    options: ["Violín", "Guitarra", "Flauta", "Piano"],
    correctIndex: 3,
  },
  {
    id: 315,
    question: "¿Qué instrumento tiene seis cuerdas habitualmente?",
    options: ["Piano", "Batería", "Trompeta", "Guitarra"],
    correctIndex: 3,
  },
  {
    id: 316,
    question: "¿Qué arte se realiza normalmente con una cámara?",
    options: ["Fotografía", "Cerámica", "Escultura", "Grabado"],
    correctIndex: 0,
  },
  {
    id: 317,
    question: "¿Qué profesión dirige una orquesta?",
    options: ["Arquitecto", "Editor", "Pintor", "Director de orquesta"],
    correctIndex: 3,
  },
  {
    id: 318,
    question: "¿Cuál es el idioma oficial principal de Brasil?",
    options: ["Italiano", "Español", "Francés", "Portugués"],
    correctIndex: 3,
  },
  {
    id: 319,
    question: "¿Cuál es el idioma oficial principal de Francia?",
    options: ["Alemán", "Francés", "Italiano", "Portugués"],
    correctIndex: 1,
  },
  {
    id: 320,
    question: "¿Cuál es el idioma oficial principal de Alemania?",
    options: ["Inglés", "Español", "Francés", "Alemán"],
    correctIndex: 3,
  },
  {
    id: 321,
    question: "¿Qué moneda se usa en la eurozona?",
    options: ["Dólar", "Euro", "Libra", "Yen"],
    correctIndex: 1,
  },
  {
    id: 322,
    question: "¿Qué moneda se usa en Estados Unidos?",
    options: ["Dólar estadounidense", "Euro", "Peso mexicano", "Yen"],
    correctIndex: 0,
  },
  {
    id: 323,
    question: "¿Qué ciudad es famosa por la Torre Eiffel?",
    options: ["Madrid", "Roma", "Berlín", "París"],
    correctIndex: 3,
  },
  {
    id: 324,
    question: "¿Qué ciudad es famosa por el Coliseo?",
    options: ["Viena", "Lisboa", "Roma", "Atenas"],
    correctIndex: 2,
  },
  {
    id: 325,
    question: "¿Qué país es famoso por las pirámides de Guiza?",
    options: ["Egipto", "Marruecos", "México", "Grecia"],
    correctIndex: 0,
  },
  {
    id: 326,
    question: "¿Qué civilización construyó Machu Picchu?",
    options: ["Inca", "Romana", "Egipcia", "Vikinga"],
    correctIndex: 0,
  },
  {
    id: 327,
    question: "¿Qué imperio construyó gran parte del Coliseo?",
    options: ["Romano", "Griego", "Persa", "Maya"],
    correctIndex: 0,
  },
  {
    id: 328,
    question: "¿Quién fue el primer emperador romano?",
    options: ["Nerón", "Trajano", "Julio César", "Augusto"],
    correctIndex: 3,
  },
  {
    id: 329,
    question: "¿En qué continente está España?",
    options: ["Europa", "África", "América", "Asia"],
    correctIndex: 0,
  },
  {
    id: 330,
    question: "¿En qué continente está Egipto?",
    options: ["África", "Oceanía", "América", "Europa"],
    correctIndex: 0,
  },
  {
    id: 331,
    question: "¿En qué continente está Japón?",
    options: ["Asia", "África", "Europa", "Oceanía"],
    correctIndex: 0,
  },
  {
    id: 332,
    question: "¿Qué país tiene forma de bota en el mapa?",
    options: ["Portugal", "Alemania", "Francia", "Italia"],
    correctIndex: 3,
  },
  {
    id: 333,
    question: "¿Qué país es conocido por el tango?",
    options: ["Argentina", "Canadá", "Noruega", "India"],
    correctIndex: 0,
  },
  {
    id: 334,
    question: "¿Qué país es conocido por el flamenco?",
    options: ["Brasil", "Suecia", "España", "Japón"],
    correctIndex: 2,
  },
  {
    id: 335,
    question: "¿Qué país es conocido por el sushi?",
    options: ["México", "Italia", "Egipto", "Japón"],
    correctIndex: 3,
  },
  {
    id: 336,
    question: "¿Qué país es conocido por la pizza napolitana?",
    options: ["Noruega", "Perú", "China", "Italia"],
    correctIndex: 3,
  },
  {
    id: 337,
    question: "¿Qué país es conocido por los tacos?",
    options: ["Portugal", "Australia", "México", "Grecia"],
    correctIndex: 2,
  },
  {
    id: 338,
    question: "¿Quién escribió Romeo y Julieta?",
    options: ["Charles Dickens", "William Shakespeare", "Mark Twain", "Jane Austen"],
    correctIndex: 1,
  },
  {
    id: 339,
    question: "¿Quién escribió La Odisea?",
    options: ["Homero", "Platón", "Sófocles", "Aristóteles"],
    correctIndex: 0,
  },
  {
    id: 340,
    question: "¿Quién compuso la Novena Sinfonía?",
    options: ["Vivaldi", "Bach", "Mozart", "Beethoven"],
    correctIndex: 3,
  },
  {
    id: 341,
    question: "¿Qué pintor es famoso por La noche estrellada?",
    options: ["Monet", "Goya", "Vincent van Gogh", "Dalí"],
    correctIndex: 2,
  },
  {
    id: 342,
    question: "¿Qué pintor español es famoso por el Guernica?",
    options: ["Pablo Picasso", "Sorolla", "Murillo", "Velázquez"],
    correctIndex: 0,
  },
  {
    id: 343,
    question: "¿Qué artista pintó Las Meninas?",
    options: ["Picasso", "Miró", "Diego Velázquez", "Goya"],
    correctIndex: 2,
  },
  {
    id: 344,
    question: "¿Qué escritor creó Sherlock Holmes?",
    options: ["Bram Stoker", "Agatha Christie", "Arthur Conan Doyle", "Jules Verne"],
    correctIndex: 2,
  },
  {
    id: 345,
    question: "¿Qué autora creó a Hercule Poirot?",
    options: ["Virginia Woolf", "Agatha Christie", "J. K. Rowling", "Mary Shelley"],
    correctIndex: 1,
  },
  {
    id: 346,
    question: "¿Qué personaje literario vive en La Mancha?",
    options: ["Hamlet", "Drácula", "Don Quijote", "Ulises"],
    correctIndex: 2,
  },
  {
    id: 347,
    question: "¿Qué ciudad española es famosa por la Alhambra?",
    options: ["Granada", "Bilbao", "Zaragoza", "Valencia"],
    correctIndex: 0,
  },
  {
    id: 348,
    question: "¿Qué ciudad española es famosa por la Sagrada Familia?",
    options: ["Córdoba", "Barcelona", "Sevilla", "Málaga"],
    correctIndex: 1,
  },
  {
    id: 349,
    question: "¿Qué ciudad española es famosa por la Mezquita-Catedral?",
    options: ["Vigo", "Toledo", "Córdoba", "León"],
    correctIndex: 2,
  },
  {
    id: 350,
    question: "¿Qué comunidad autónoma tiene como capital Santiago de Compostela?",
    options: ["Andalucía", "Aragón", "Cantabria", "Galicia"],
    correctIndex: 3,
  },
  {
    id: 351,
    question: "¿Qué lenguaje se usa principalmente para páginas web interactivas?",
    options: ["HTML", "SQL", "CSS", "JavaScript"],
    correctIndex: 3,
  },
  {
    id: 352,
    question: "¿Qué lenguaje se usa para estructurar el contenido de una página web?",
    options: ["HTML", "Python", "CSS", "Java"],
    correctIndex: 0,
  },
  {
    id: 353,
    question: "¿Qué lenguaje se usa principalmente para aplicar estilos en una web?",
    options: ["HTML", "SQL", "CSS", "C"],
    correctIndex: 2,
  },
  {
    id: 354,
    question: "¿Qué significa CPU?",
    options: ["Unidad central de procesamiento", "Tarjeta gráfica", "Sistema operativo", "Memoria externa"],
    correctIndex: 0,
  },
  {
    id: 355,
    question: "¿Qué componente se encarga principalmente de los gráficos?",
    options: ["CPU", "RAM", "SSD", "GPU"],
    correctIndex: 3,
  },
  {
    id: 356,
    question: "¿Qué memoria es volátil y se usa mientras el ordenador está encendido?",
    options: ["USB", "RAM", "ROM", "SSD"],
    correctIndex: 1,
  },
  {
    id: 357,
    question: "¿Qué dispositivo almacena datos de forma permanente?",
    options: ["Monitor", "CPU", "RAM", "SSD"],
    correctIndex: 3,
  },
  {
    id: 358,
    question: "¿Qué protocolo se usa habitualmente para páginas web seguras?",
    options: ["HTTPS", "SMTP", "FTP", "POP3"],
    correctIndex: 0,
  },
  {
    id: 359,
    question: "¿Qué protocolo se usa habitualmente para enviar correos?",
    options: ["SSH", "SMTP", "HTTP", "DNS"],
    correctIndex: 1,
  },
  {
    id: 360,
    question: "¿Qué sistema traduce nombres de dominio a direcciones IP?",
    options: ["USB", "HTML", "GPU", "DNS"],
    correctIndex: 3,
  },
  {
    id: 361,
    question: "¿Qué comando se usa comúnmente para clonar un repositorio Git?",
    options: ["git init clone", "git pullall", "git copy", "git clone"],
    correctIndex: 3,
  },
  {
    id: 362,
    question: "¿Qué comando de Git crea una confirmación de cambios?",
    options: ["git push", "git fetch", "git commit", "git merge"],
    correctIndex: 2,
  },
  {
    id: 363,
    question: "¿Qué comando de Git sube cambios a un remoto?",
    options: ["git status", "git push", "git log", "git diff"],
    correctIndex: 1,
  },
  {
    id: 364,
    question: "¿Qué comando de Git muestra el estado del repositorio?",
    options: ["git clone", "git commit", "git reset", "git status"],
    correctIndex: 3,
  },
  {
    id: 365,
    question: "¿Qué base de datos usa tablas y SQL habitualmente?",
    options: ["Documento únicamente", "Clave secreta", "Relacional", "Vectorial pura"],
    correctIndex: 2,
  },
  {
    id: 366,
    question: "¿Qué significa API?",
    options: ["Acceso público inmediato", "Interfaz de programación de aplicaciones", "Archivo privado interno", "Aplicación para imágenes"],
    correctIndex: 1,
  },
  {
    id: 367,
    question: "¿Qué formato de datos usa llaves y pares clave-valor?",
    options: ["CSS", "PNG", "MP3", "JSON"],
    correctIndex: 3,
  },
  {
    id: 368,
    question: "¿Qué etiqueta HTML crea un enlace?",
    options: ["span", "p", "a", "div"],
    correctIndex: 2,
  },
  {
    id: 369,
    question: "¿Qué etiqueta HTML muestra una imagen?",
    options: ["img", "section", "button", "input"],
    correctIndex: 0,
  },
  {
    id: 370,
    question: "¿Qué método HTTP se usa normalmente para obtener datos?",
    options: ["DELETE", "PATCH", "POST", "GET"],
    correctIndex: 3,
  },
  {
    id: 371,
    question: "¿Qué método HTTP se usa normalmente para crear/enviar datos?",
    options: ["HEAD", "GET", "POST", "OPTIONS"],
    correctIndex: 2,
  },
  {
    id: 372,
    question: "¿Qué código HTTP indica que no se ha encontrado un recurso?",
    options: ["500", "301", "200", "404"],
    correctIndex: 3,
  },
  {
    id: 373,
    question: "¿Qué código HTTP indica éxito normalmente?",
    options: ["200", "404", "403", "500"],
    correctIndex: 0,
  },
  {
    id: 374,
    question: "¿Qué código HTTP indica error interno del servidor?",
    options: ["301", "201", "500", "204"],
    correctIndex: 2,
  },
  {
    id: 375,
    question: "¿Qué significa URL?",
    options: ["Usuario remoto libre", "Uso reducido lógico", "Unidad rápida local", "Localizador uniforme de recursos"],
    correctIndex: 3,
  },
  {
    id: 376,
    question: "¿Qué servicio se usa para controlar versiones de código?",
    options: ["Git", "Excel", "Photoshop", "PowerPoint"],
    correctIndex: 0,
  },
  {
    id: 377,
    question: "¿Qué herramienta permite crear interfaces declarativas con componentes?",
    options: ["Nginx", "Docker", "MySQL", "React"],
    correctIndex: 3,
  },
  {
    id: 378,
    question: "¿Qué entorno ejecuta JavaScript en servidor?",
    options: ["Node.js", "Excel", "Figma", "Photoshop"],
    correctIndex: 0,
  },
  {
    id: 379,
    question: "¿Qué comando instala dependencias en proyectos Node?",
    options: ["git install", "node build", "npm start all", "npm install"],
    correctIndex: 3,
  },
  {
    id: 380,
    question: "¿Qué archivo suele listar dependencias en un proyecto Node?",
    options: ["server.docx", "index.html", "package.json", "README.png"],
    correctIndex: 2,
  },
  {
    id: 381,
    question: "¿Qué tecnología permite aislar aplicaciones en contenedores?",
    options: ["SMTP", "CSS", "Docker", "Git"],
    correctIndex: 2,
  },
  {
    id: 382,
    question: "¿Qué servidor web se usa a menudo como proxy inverso?",
    options: ["Nginx", "Word", "Notepad", "Excel"],
    correctIndex: 0,
  },
  {
    id: 383,
    question: "¿Qué significa IA?",
    options: ["Instalación automática", "Interfaz analógica", "Inteligencia artificial", "Internet abierto"],
    correctIndex: 2,
  },
  {
    id: 384,
    question: "¿Qué tipo de archivo suele terminar en .js?",
    options: ["Vídeo", "JavaScript", "Hoja de cálculo", "Imagen"],
    correctIndex: 1,
  },
  {
    id: 385,
    question: "¿Qué tipo de archivo suele terminar en .css?",
    options: ["Ejecutable", "Hoja de estilos", "Audio", "Base de datos"],
    correctIndex: 1,
  },
  {
    id: 386,
    question: "¿Qué tipo de archivo suele terminar en .html?",
    options: ["Audio", "Imagen comprimida", "Vídeo", "Documento web"],
    correctIndex: 3,
  },
  {
    id: 387,
    question: "¿Qué extensión suele tener una imagen PNG?",
    options: [".png", ".mp3", ".xlsx", ".exe"],
    correctIndex: 0,
  },
  {
    id: 388,
    question: "¿Qué extensión suele tener un documento PDF?",
    options: [".pdf", ".json", ".wav", ".css"],
    correctIndex: 0,
  },
  {
    id: 389,
    question: "¿Qué herramienta de Microsoft se usa para automatizar flujos?",
    options: ["Teams Classic únicamente", "Power Automate", "Notepad", "Paint"],
    correctIndex: 1,
  },
  {
    id: 390,
    question: "¿Qué herramienta de Microsoft se usa para crear informes interactivos?",
    options: ["Power BI", "OneNote únicamente", "WordPad", "Paint"],
    correctIndex: 0,
  },
  {
    id: 391,
    question: "¿Qué herramienta de Microsoft se usa para listas y sitios colaborativos?",
    options: ["PowerPoint", "SharePoint", "Clipchamp", "Calculadora"],
    correctIndex: 1,
  },
  {
    id: 392,
    question: "¿Qué operador lógico requiere que dos condiciones sean verdaderas?",
    options: ["OR", "AND", "XOR siempre", "NOT"],
    correctIndex: 1,
  },
  {
    id: 393,
    question: "¿Qué operador lógico permite que al menos una condición sea verdadera?",
    options: ["OR", "NULL", "AND", "NOT"],
    correctIndex: 0,
  },
  {
    id: 394,
    question: "¿Qué valor booleano representa verdadero?",
    options: ["null", "false", "undefined", "true"],
    correctIndex: 3,
  },
  {
    id: 395,
    question: "¿Qué valor booleano representa falso?",
    options: ["true", "sí", "false", "1 siempre"],
    correctIndex: 2,
  },
  {
    id: 396,
    question: "¿Qué palabra clave de JavaScript declara una constante?",
    options: ["fixed", "const", "variante", "statico"],
    correctIndex: 1,
  },
  {
    id: 397,
    question: "¿Qué palabra clave de JavaScript declara una variable reasignable moderna?",
    options: ["const", "let", "class", "return"],
    correctIndex: 1,
  },
  {
    id: 398,
    question: "¿Qué estructura permite repetir instrucciones?",
    options: ["Bucle", "Condición únicamente", "Importación", "Comentario"],
    correctIndex: 0,
  },
  {
    id: 399,
    question: "¿Qué estructura permite elegir entre caminos según una condición?",
    options: ["CSS", "Índice", "Condicional", "Array"],
    correctIndex: 2,
  },
  {
    id: 400,
    question: "¿Qué estructura almacena varios elementos en orden?",
    options: ["Número suelto", "Comentario", "Booleano", "Array"],
    correctIndex: 3,
  },
  {
    id: 401,
    question: "¿Cuál es el resultado de 101 - 3?",
    options: ["100", "97", "98", "99"],
    correctIndex: 2,
  },
  {
    id: 402,
    question: "¿Cuánto es el 10% de 1200?",
    options: ["110", "120", "125", "140"],
    correctIndex: 1,
  },
  {
    id: 403,
    question: "Si un lado de un cuadrado mide 8 cm, ¿cuál es su área?",
    options: ["64 cm²", "56 cm²", "72 cm²", "66 cm²"],
    correctIndex: 0,
  },
  {
    id: 404,
    question: "¿Cuál es el cuadrado de 24?",
    options: ["586", "600", "552", "576"],
    correctIndex: 3,
  },
  {
    id: 405,
    question: "¿Cuál es el resultado de 105 - 7?",
    options: ["97", "100", "99", "98"],
    correctIndex: 3,
  },
  {
    id: 406,
    question: "¿Cuánto es el 10% de 1600?",
    options: ["160", "150", "165", "180"],
    correctIndex: 0,
  },
  {
    id: 407,
    question: "Si un lado de un cuadrado mide 12 cm, ¿cuál es su área?",
    options: ["144 cm²", "132 cm²", "146 cm²", "156 cm²"],
    correctIndex: 0,
  },
  {
    id: 408,
    question: "¿Cuál es el cuadrado de 28?",
    options: ["812", "756", "784", "794"],
    correctIndex: 2,
  },
  {
    id: 409,
    question: "¿Cuál es el resultado de 109 - 2?",
    options: ["107", "108", "109", "106"],
    correctIndex: 0,
  },
  {
    id: 410,
    question: "¿Cuánto es el 10% de 2000?",
    options: ["205", "220", "200", "190"],
    correctIndex: 2,
  },
  {
    id: 411,
    question: "Si un lado de un cuadrado mide 16 cm, ¿cuál es su área?",
    options: ["258 cm²", "240 cm²", "272 cm²", "256 cm²"],
    correctIndex: 3,
  },
  {
    id: 412,
    question: "¿Cuál es el cuadrado de 32?",
    options: ["992", "1034", "1024", "1056"],
    correctIndex: 2,
  },
  {
    id: 413,
    question: "¿Cuál es el resultado de 113 - 6?",
    options: ["108", "106", "107", "109"],
    correctIndex: 2,
  },
  {
    id: 414,
    question: "¿Cuánto es el 10% de 2400?",
    options: ["260", "230", "240", "245"],
    correctIndex: 2,
  },
  {
    id: 415,
    question: "Si un lado de un cuadrado mide 5 cm, ¿cuál es su área?",
    options: ["30 cm²", "25 cm²", "27 cm²", "20 cm²"],
    correctIndex: 1,
  },
  {
    id: 416,
    question: "¿Cuál es el cuadrado de 36?",
    options: ["1332", "1260", "1296", "1306"],
    correctIndex: 2,
  },
  {
    id: 417,
    question: "¿Cuál es el resultado de 117 - 10?",
    options: ["109", "107", "106", "108"],
    correctIndex: 1,
  },
  {
    id: 418,
    question: "¿Cuánto es el 10% de 2800?",
    options: ["270", "285", "280", "300"],
    correctIndex: 2,
  },
  {
    id: 419,
    question: "Si un lado de un cuadrado mide 9 cm, ¿cuál es su área?",
    options: ["81 cm²", "90 cm²", "72 cm²", "83 cm²"],
    correctIndex: 0,
  },
  {
    id: 420,
    question: "¿Cuál es el cuadrado de 40?",
    options: ["1640", "1560", "1600", "1610"],
    correctIndex: 2,
  },
  {
    id: 421,
    question: "¿Cuál es el resultado de 121 - 5?",
    options: ["118", "116", "117", "115"],
    correctIndex: 1,
  },
  {
    id: 422,
    question: "¿Cuánto es el 10% de 1200?",
    options: ["120", "125", "140", "110"],
    correctIndex: 0,
  },
  {
    id: 423,
    question: "Si un lado de un cuadrado mide 13 cm, ¿cuál es su área?",
    options: ["182 cm²", "156 cm²", "169 cm²", "171 cm²"],
    correctIndex: 2,
  },
  {
    id: 424,
    question: "¿Cuál es el cuadrado de 44?",
    options: ["1892", "1936", "1946", "1980"],
    correctIndex: 1,
  },
  {
    id: 425,
    question: "¿Cuál es el resultado de 125 - 9?",
    options: ["115", "116", "117", "118"],
    correctIndex: 1,
  },
  {
    id: 426,
    question: "¿Cuánto es el 10% de 1600?",
    options: ["150", "180", "165", "160"],
    correctIndex: 3,
  },
  {
    id: 427,
    question: "Si un lado de un cuadrado mide 17 cm, ¿cuál es su área?",
    options: ["272 cm²", "289 cm²", "291 cm²", "306 cm²"],
    correctIndex: 1,
  },
  {
    id: 428,
    question: "¿Cuál es el cuadrado de 48?",
    options: ["2304", "2256", "2314", "2352"],
    correctIndex: 0,
  },
  {
    id: 429,
    question: "¿Cuál es el resultado de 129 - 4?",
    options: ["124", "127", "126", "125"],
    correctIndex: 3,
  },
  {
    id: 430,
    question: "¿Cuánto es el 10% de 2000?",
    options: ["200", "205", "190", "220"],
    correctIndex: 0,
  },
  {
    id: 431,
    question: "Si un lado de un cuadrado mide 6 cm, ¿cuál es su área?",
    options: ["42 cm²", "38 cm²", "36 cm²", "30 cm²"],
    correctIndex: 2,
  },
  {
    id: 432,
    question: "¿Cuál es el cuadrado de 52?",
    options: ["2714", "2756", "2704", "2652"],
    correctIndex: 2,
  },
  {
    id: 433,
    question: "¿Cuál es el resultado de 133 - 8?",
    options: ["127", "124", "125", "126"],
    correctIndex: 2,
  },
  {
    id: 434,
    question: "¿Cuánto es el 10% de 2400?",
    options: ["260", "240", "245", "230"],
    correctIndex: 1,
  },
  {
    id: 435,
    question: "Si un lado de un cuadrado mide 10 cm, ¿cuál es su área?",
    options: ["90 cm²", "110 cm²", "102 cm²", "100 cm²"],
    correctIndex: 3,
  },
  {
    id: 436,
    question: "¿Cuál es el cuadrado de 56?",
    options: ["3080", "3146", "3136", "3192"],
    correctIndex: 2,
  },
  {
    id: 437,
    question: "¿Cuál es el resultado de 137 - 3?",
    options: ["133", "136", "135", "134"],
    correctIndex: 3,
  },
  {
    id: 438,
    question: "¿Cuánto es el 10% de 2800?",
    options: ["285", "300", "280", "270"],
    correctIndex: 2,
  },
  {
    id: 439,
    question: "Si un lado de un cuadrado mide 14 cm, ¿cuál es su área?",
    options: ["182 cm²", "210 cm²", "198 cm²", "196 cm²"],
    correctIndex: 3,
  },
  {
    id: 440,
    question: "¿Cuál es el cuadrado de 60?",
    options: ["3660", "3610", "3540", "3600"],
    correctIndex: 3,
  },
  {
    id: 441,
    question: "¿Cuál es el resultado de 141 - 7?",
    options: ["134", "133", "136", "135"],
    correctIndex: 0,
  },
  {
    id: 442,
    question: "¿Cuánto es el 10% de 1200?",
    options: ["140", "125", "110", "120"],
    correctIndex: 3,
  },
  {
    id: 443,
    question: "Si un lado de un cuadrado mide 18 cm, ¿cuál es su área?",
    options: ["326 cm²", "324 cm²", "306 cm²", "342 cm²"],
    correctIndex: 1,
  },
  {
    id: 444,
    question: "¿Cuál es el cuadrado de 64?",
    options: ["4160", "4106", "4096", "4032"],
    correctIndex: 2,
  },
  {
    id: 445,
    question: "¿Cuál es el resultado de 145 - 2?",
    options: ["142", "143", "144", "145"],
    correctIndex: 1,
  },
  {
    id: 446,
    question: "¿Cuánto es el 10% de 1600?",
    options: ["160", "150", "165", "180"],
    correctIndex: 0,
  },
  {
    id: 447,
    question: "Si un lado de un cuadrado mide 7 cm, ¿cuál es su área?",
    options: ["56 cm²", "51 cm²", "49 cm²", "42 cm²"],
    correctIndex: 2,
  },
  {
    id: 448,
    question: "¿Cuál es el cuadrado de 68?",
    options: ["4692", "4634", "4624", "4556"],
    correctIndex: 2,
  },
  {
    id: 449,
    question: "¿Cuál es el resultado de 149 - 6?",
    options: ["143", "144", "145", "142"],
    correctIndex: 0,
  },
  {
    id: 450,
    question: "¿Cuánto es el 10% de 2000?",
    options: ["200", "220", "190", "205"],
    correctIndex: 0,
  },
  {
    id: 451,
    question: "Si un lado de un cuadrado mide 11 cm, ¿cuál es su área?",
    options: ["110 cm²", "123 cm²", "121 cm²", "132 cm²"],
    correctIndex: 2,
  },
  {
    id: 452,
    question: "¿Cuál es el cuadrado de 72?",
    options: ["5112", "5194", "5256", "5184"],
    correctIndex: 3,
  },
  {
    id: 453,
    question: "¿Cuál es el resultado de 153 - 10?",
    options: ["144", "142", "145", "143"],
    correctIndex: 3,
  },
  {
    id: 454,
    question: "¿Cuánto es el 10% de 2400?",
    options: ["240", "260", "245", "230"],
    correctIndex: 0,
  },
  {
    id: 455,
    question: "Si un lado de un cuadrado mide 15 cm, ¿cuál es su área?",
    options: ["225 cm²", "210 cm²", "227 cm²", "240 cm²"],
    correctIndex: 0,
  },
  {
    id: 456,
    question: "¿Cuál es el cuadrado de 76?",
    options: ["5786", "5852", "5700", "5776"],
    correctIndex: 3,
  },
  {
    id: 457,
    question: "¿Cuál es el resultado de 157 - 5?",
    options: ["154", "153", "152", "151"],
    correctIndex: 2,
  },
  {
    id: 458,
    question: "¿Cuánto es el 10% de 2800?",
    options: ["280", "270", "285", "300"],
    correctIndex: 0,
  },
  {
    id: 459,
    question: "Si un lado de un cuadrado mide 19 cm, ¿cuál es su área?",
    options: ["361 cm²", "380 cm²", "342 cm²", "363 cm²"],
    correctIndex: 0,
  },
  {
    id: 460,
    question: "¿Cuál es el cuadrado de 80?",
    options: ["6400", "6480", "6410", "6320"],
    correctIndex: 0,
  },
  {
    id: 461,
    question: "¿Cuál es el resultado de 161 - 9?",
    options: ["154", "153", "151", "152"],
    correctIndex: 3,
  },
  {
    id: 462,
    question: "¿Cuánto es el 10% de 1200?",
    options: ["110", "140", "125", "120"],
    correctIndex: 3,
  },
  {
    id: 463,
    question: "Si un lado de un cuadrado mide 8 cm, ¿cuál es su área?",
    options: ["66 cm²", "56 cm²", "72 cm²", "64 cm²"],
    correctIndex: 3,
  },
  {
    id: 464,
    question: "¿Cuál es el cuadrado de 84?",
    options: ["7056", "7066", "7140", "6972"],
    correctIndex: 0,
  },
  {
    id: 465,
    question: "¿Cuál es el resultado de 165 - 4?",
    options: ["161", "163", "160", "162"],
    correctIndex: 0,
  },
  {
    id: 466,
    question: "¿Cuánto es el 10% de 1600?",
    options: ["180", "160", "165", "150"],
    correctIndex: 1,
  },
  {
    id: 467,
    question: "Si un lado de un cuadrado mide 12 cm, ¿cuál es su área?",
    options: ["156 cm²", "144 cm²", "146 cm²", "132 cm²"],
    correctIndex: 1,
  },
  {
    id: 468,
    question: "¿Cuál es el cuadrado de 88?",
    options: ["7754", "7832", "7656", "7744"],
    correctIndex: 3,
  },
  {
    id: 469,
    question: "¿Cuál es el resultado de 169 - 8?",
    options: ["162", "161", "163", "160"],
    correctIndex: 1,
  },
  {
    id: 470,
    question: "¿Cuánto es el 10% de 2000?",
    options: ["190", "205", "220", "200"],
    correctIndex: 3,
  },
  {
    id: 471,
    question: "Si un lado de un cuadrado mide 16 cm, ¿cuál es su área?",
    options: ["256 cm²", "258 cm²", "240 cm²", "272 cm²"],
    correctIndex: 0,
  },
  {
    id: 472,
    question: "¿Cuál es el cuadrado de 92?",
    options: ["8474", "8464", "8556", "8372"],
    correctIndex: 1,
  },
  {
    id: 473,
    question: "¿Cuál es el resultado de 173 - 3?",
    options: ["170", "172", "169", "171"],
    correctIndex: 0,
  },
  {
    id: 474,
    question: "¿Cuánto es el 10% de 2400?",
    options: ["240", "260", "245", "230"],
    correctIndex: 0,
  },
  {
    id: 475,
    question: "Si un lado de un cuadrado mide 5 cm, ¿cuál es su área?",
    options: ["25 cm²", "27 cm²", "30 cm²", "20 cm²"],
    correctIndex: 0,
  },
  {
    id: 476,
    question: "¿Cuál es el cuadrado de 96?",
    options: ["9312", "9226", "9216", "9120"],
    correctIndex: 2,
  },
  {
    id: 477,
    question: "¿Cuál es el resultado de 177 - 7?",
    options: ["171", "172", "169", "170"],
    correctIndex: 3,
  },
  {
    id: 478,
    question: "¿Cuánto es el 10% de 2800?",
    options: ["280", "285", "270", "300"],
    correctIndex: 0,
  },
  {
    id: 479,
    question: "Si un lado de un cuadrado mide 9 cm, ¿cuál es su área?",
    options: ["72 cm²", "90 cm²", "81 cm²", "83 cm²"],
    correctIndex: 2,
  },
  {
    id: 480,
    question: "¿Cuál es el cuadrado de 100?",
    options: ["10100", "9900", "10000", "10010"],
    correctIndex: 2,
  },
  {
    id: 481,
    question: "¿Cuál es el resultado de 181 - 2?",
    options: ["178", "181", "179", "180"],
    correctIndex: 2,
  },
  {
    id: 482,
    question: "¿Cuánto es el 10% de 1200?",
    options: ["120", "140", "110", "125"],
    correctIndex: 0,
  },
  {
    id: 483,
    question: "Si un lado de un cuadrado mide 13 cm, ¿cuál es su área?",
    options: ["182 cm²", "169 cm²", "171 cm²", "156 cm²"],
    correctIndex: 1,
  },
  {
    id: 484,
    question: "¿Cuál es el cuadrado de 104?",
    options: ["10826", "10816", "10920", "10712"],
    correctIndex: 1,
  },
  {
    id: 485,
    question: "¿Cuál es el resultado de 185 - 6?",
    options: ["178", "179", "181", "180"],
    correctIndex: 1,
  },
  {
    id: 486,
    question: "¿Cuánto es el 10% de 1600?",
    options: ["165", "150", "180", "160"],
    correctIndex: 3,
  },
  {
    id: 487,
    question: "Si un lado de un cuadrado mide 17 cm, ¿cuál es su área?",
    options: ["289 cm²", "306 cm²", "291 cm²", "272 cm²"],
    correctIndex: 0,
  },
  {
    id: 488,
    question: "¿Cuál es el cuadrado de 108?",
    options: ["11772", "11664", "11556", "11674"],
    correctIndex: 1,
  },
  {
    id: 489,
    question: "¿Cuál es el resultado de 189 - 10?",
    options: ["178", "180", "181", "179"],
    correctIndex: 3,
  },
  {
    id: 490,
    question: "¿Cuánto es el 10% de 2000?",
    options: ["200", "205", "190", "220"],
    correctIndex: 0,
  },
  {
    id: 491,
    question: "Si un lado de un cuadrado mide 6 cm, ¿cuál es su área?",
    options: ["30 cm²", "36 cm²", "38 cm²", "42 cm²"],
    correctIndex: 1,
  },
  {
    id: 492,
    question: "¿Cuál es el cuadrado de 112?",
    options: ["12544", "12432", "12656", "12554"],
    correctIndex: 0,
  },
  {
    id: 493,
    question: "¿Cuál es el resultado de 193 - 5?",
    options: ["190", "188", "187", "189"],
    correctIndex: 1,
  },
  {
    id: 494,
    question: "¿Cuánto es el 10% de 2400?",
    options: ["230", "240", "260", "245"],
    correctIndex: 1,
  },
  {
    id: 495,
    question: "Si un lado de un cuadrado mide 10 cm, ¿cuál es su área?",
    options: ["110 cm²", "102 cm²", "100 cm²", "90 cm²"],
    correctIndex: 2,
  },
  {
    id: 496,
    question: "¿Cuál es el cuadrado de 116?",
    options: ["13572", "13456", "13466", "13340"],
    correctIndex: 1,
  },
  {
    id: 497,
    question: "¿Cuál es el resultado de 197 - 9?",
    options: ["188", "189", "190", "187"],
    correctIndex: 0,
  },
  {
    id: 498,
    question: "¿Cuánto es el 10% de 2800?",
    options: ["270", "300", "285", "280"],
    correctIndex: 3,
  },
  {
    id: 499,
    question: "Si un lado de un cuadrado mide 14 cm, ¿cuál es su área?",
    options: ["210 cm²", "198 cm²", "182 cm²", "196 cm²"],
    correctIndex: 3,
  },
  {
    id: 500,
    question: "¿Cuál es el cuadrado de 120?",
    options: ["14280", "14410", "14400", "14520"],
    correctIndex: 2,
  },
];

function getRandomQuestion() {
  const index = Math.floor(Math.random() * questions.length);
  return questions[index];
}

module.exports = {
  questions,
  getRandomQuestion,
};